"""Security review rules based on OWASP Top 10 and CWE.

All rules in this module are DETERMINISTIC - they use regex/AST pattern
matching and do NOT require LLM judgment.
"""

SECURITY_RULES = [
    # SQL Injection
    {
        "rule_id": "SEC-001",
        "name": "SQL Injection via String Concatenation",
        "category": "security",
        "severity": "critical",
        "language": "all",
        "description": "SQL query built with string concatenation from variables — potential SQL injection.",
        "pattern": r'(?:execute|query|raw)\s*\(\s*(?:f["\']|["\'].*?%.*?["\']|["\'].*?\+\s*\w|["\'].*?\.format\()',
        "is_deterministic": True,
        "cwe_id": "CWE-89",
        "owasp_category": "A03:2021-Injection",
        "fix_suggestion": "Use parameterized queries with placeholders (? or %s) instead of string concatenation.",
    },
    {
        "rule_id": "SEC-002",
        "name": "Hardcoded Secret / API Key",
        "category": "security",
        "severity": "critical",
        "language": "all",
        "description": "Hardcoded API keys, passwords, or tokens found in source code.",
        "pattern": r'(?:api_key|api_secret|secret_key|password|token|auth_token)\s*[:=]\s*["\'][A-Za-z0-9_\-\.]{16,}["\']',
        "is_deterministic": True,
        "cwe_id": "CWE-798",
        "owasp_category": "A07:2021-Identification Failures",
        "fix_suggestion": "Use environment variables or a secrets manager (e.g., HashiCorp Vault, AWS Secrets Manager).",
    },
    {
        "rule_id": "SEC-003",
        "name": "Command Injection via Shell Execution",
        "category": "security",
        "severity": "critical",
        "language": "all",
        "description": "Shell command execution with user-controlled input — potential command injection.",
        "pattern": r'(?:os\.system|os\.popen|subprocess\.(?:call|Popen|run|check_output))\s*\(.*?(?:request|input|param|argv|environ|body|query)',
        "is_deterministic": True,
        "cwe_id": "CWE-78",
        "owasp_category": "A03:2021-Injection",
        "fix_suggestion": "Use subprocess.run() with a list of arguments (not a shell string) and avoid shell=True.",
    },
    {
        "rule_id": "SEC-004",
        "name": "Path Traversal Vulnerability",
        "category": "security",
        "severity": "critical",
        "language": "all",
        "description": "File path constructed from user input without sanitization — potential path traversal.",
        "pattern": r'(?:open|read|write|read_file|write_file)\s*\(.*?(?:\.\./|\.\.\\)',
        "is_deterministic": True,
        "cwe_id": "CWE-22",
        "owasp_category": "A01:2021-Broken Access Control",
        "fix_suggestion": "Use os.path.realpath() to resolve and validate that the resolved path stays within the allowed directory.",
    },
    {
        "rule_id": "SEC-005",
        "name": "XSS via innerHTML / document.write",
        "category": "security",
        "severity": "major",
        "language": "javascript",
        "description": "User input directly assigned to innerHTML or document.write — potential XSS.",
        "pattern": r'(?:innerHTML|outerHTML|document\.write)\s*[=\(]\s*(?:req|request|input|param|query|search|hash)',
        "is_deterministic": True,
        "cwe_id": "CWE-79",
        "owasp_category": "A03:2021-Injection",
        "fix_suggestion": "Use textContent instead of innerHTML, or sanitize with DOMPurify before assignment.",
    },
    {
        "rule_id": "SEC-006",
        "name": "Insecure Deserialization",
        "category": "security",
        "severity": "critical",
        "language": "all",
        "description": "Using unsafe deserialization functions that can execute arbitrary code.",
        "pattern": r'(?:pickle\.loads?|yaml\.load\s*\(|marshal\.loads?|eval\s*\(|exec\s*\()',
        "is_deterministic": True,
        "cwe_id": "CWE-502",
        "owasp_category": "A08:2021-Software and Data Integrity Failures",
        "fix_suggestion": "Use safe alternatives: json.loads() instead of pickle, yaml.safe_load() instead of yaml.load().",
    },
    {
        "rule_id": "SEC-007",
        "name": "Weak Cryptographic Algorithm",
        "category": "security",
        "severity": "major",
        "language": "all",
        "description": "Using deprecated or weak cryptographic algorithms (MD5, SHA1, DES).",
        "pattern": r'(?:MD5|SHA1|SHA-1|DES|RC4|RC2|3DES)\s*(?:\(|\.|:|\s*=\s*)',
        "is_deterministic": True,
        "cwe_id": "CWE-327",
        "owasp_category": "A02:2021-Cryptographic Failures",
        "fix_suggestion": "Use SHA-256 or better for hashing, AES-GCM for encryption.",
    },
    {
        "rule_id": "SEC-008",
        "name": "Missing TLS/SSL Certificate Validation",
        "category": "security",
        "severity": "major",
        "language": "all",
        "description": "HTTP client with SSL verification disabled — susceptible to MITM attacks.",
        "pattern": r'(?:verify\s*=\s*False|verify=False|ssl\.CERT_NONE|rejectUnauthorized.*false|InsecureRequestWarning)',
        "is_deterministic": True,
        "cwe_id": "CWE-295",
        "owasp_category": "A02:2021-Cryptographic Failures",
        "fix_suggestion": "Remove verify=False and ensure proper certificate validation. In development, use a proper CA or self-signed cert.",
    },
    {
        "rule_id": "SEC-009",
        "name": "Open Redirect Vulnerability",
        "category": "security",
        "severity": "major",
        "language": "all",
        "description": "Redirect URL taken from user input without validation — potential open redirect.",
        "pattern": r'(?:redirect|RedirectResponse|Location)\s*[\(:]\s*(?:request|req|params|query|body)',
        "is_deterministic": True,
        "cwe_id": "CWE-601",
        "owasp_category": "A01:2021-Broken Access Control",
        "fix_suggestion": "Validate redirect URLs against a whitelist of allowed domains. Reject absolute URLs.",
    },
    {
        "rule_id": "SEC-010",
        "name": "Server-Side Request Forgery (SSRF)",
        "category": "security",
        "severity": "critical",
        "language": "all",
        "description": "URL fetched from user input without validation — potential SSRF.",
        "pattern": r'(?:requests\.(?:get|post|put|delete)|urllib\.request\.urlopen|fetch\s*\(|axios\.(?:get|post))\s*\(.*?(?:request|input|param|query|body)',
        "is_deterministic": True,
        "cwe_id": "CWE-918",
        "owasp_category": "A10:2021-Server-Side Request Forgery",
        "fix_suggestion": "Validate and sanitize URLs: block internal IPs (127.0.0.1, 10.x, 192.168.x), use allowlists for domains.",
    },
]
